version: "3.5"

services:
   mongodb:
      container_name: phis-mongodb
      image: 'mongo:4.2'
      networks:
         - phis-services
      labels:
         kompose.service.type: nodeport
      ports:
         - "27017"
      volumes:
         - phis-mongodb-data:/data/db

   postgres:
      container_name: phis-postgres
      build: ./postgres
      networks:
         - phis-services
      ports:
         - "5432"
      environment:
         - POSTGRES_PASSWORD=azerty
         - POSTGRES_USER=phis
         - POSTGRES_DB=phis
      volumes:
         - phis-postgresql-data:/var/lib/postgresql/data

   rdf4j:
      container_name: phis-rdf4j
      build: './rdf4j'
      networks:
         - phis-services
      ports:
         - "8080"
      volumes:
         - phis-rdf4j-data:/var/rdf4j
      environment:
         - JAVA_OPTS='-Dorg.eclipse.rdf4j.appdata.basedir=/var/rdf4j/'
      
   phis-webapp:
      container_name: phis-webapp
      build: ./phis-webapp
      networks:
         - phis-services
         - web-network
      ports:
         - "80"
      volumes:
         - phis-web-data:/var/www/html/
      environment:
         - PHIS_WS_URL=http://phis-ws:8080/phis2ws
         - PHIS_WEBAPP_HOST=phis.traitcapture.org
         - PHIS_WEBAPP_PORT=80

   phis-ws:
      container_name: phis-ws
      build: 
         context: ./phis-ws
         args: 
            PHIS_WS_HOST: phisws.traitcapture.org
            PHIS_WS_PORT: 80
            PHIS_WEBAPP_HOST: phis.traitcapture.org
            PHIS_WEBAPP_PORT: 80
            MONGO_HOST: mongodb
            MONGO_PORT: 27017
            PG_HOST: postgres
            PG_PORT: 5432
            RDF4J_HOST: rdf4j
            RDF4J_PORT: 8080
            BASE_URI: https://phis.traitcapture.org/
      networks:
         - phis-services      
         - web-network
      depends_on:
         - "rdf4j"
         - "mongodb"
         - "postgres"
      ports:
         - "8080"
      volumes:
         - phis-ws-docs:/home/phis/documents
         - phis-ws-logs:/home/phis/logs

networks:
   
   
   web-network:
      external: true
      name: web-network
   phis-services:
      external: true
      name: phis-services
volumes:
   phis-postgresql-data:
   phis-mongodb-data:
   phis-rdf4j-data:
   phis-web-data:
   phis-ws-docs:
   phis-ws-logs:
